version: '3.8'
services:
  translate-service:
    image: translate-service
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_PORT=5432
      - DB_HOST=postgresdb
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - API_YANDEX_TRANSLATE_API_KEY=$YANDEX_API_KEY
    restart: always
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - 5432:5433
    volumes:
      - db:/var/lib/postgres

volumes:
  db: